SELECT DISTINCT ?item WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
  {
    SELECT DISTINCT ?item WHERE {
      ?item p:P463 ?statement0.
      ?statement0 (ps:P463/(wdt:P279*)) wd:Q106489997.
    }
    LIMIT 100
  }
}